apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app: my-app
spec:
  type: LoadBalancer
  selector:                
    app: my-app            
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
